USE [master]
GO

/****** Object:  Database [WPF_menu_rights]    Script Date: 10/27/2015 20:02:41 ******/
CREATE DATABASE [WPF_menu_rights] ON  PRIMARY 
( NAME = N'WPF_menu_rights', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\WPF_menu_rights.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WPF_menu_rights_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\WPF_menu_rights_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WPF_menu_rights] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WPF_menu_rights].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WPF_menu_rights] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET ARITHABORT OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [WPF_menu_rights] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WPF_menu_rights] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WPF_menu_rights] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WPF_menu_rights] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WPF_menu_rights] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WPF_menu_rights] SET  READ_WRITE 
GO

ALTER DATABASE [WPF_menu_rights] SET RECOVERY FULL 
GO

ALTER DATABASE [WPF_menu_rights] SET  MULTI_USER 
GO

ALTER DATABASE [WPF_menu_rights] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WPF_menu_rights] SET DB_CHAINING OFF 
GO

